export const USER_DATA = [
  {
    id: 49798,
    name: "Abdallaha Abdi  Mushi",
    email: "abdallah.mushi2@afya.go.tz",
    created_at: "2019-11-15 10:53:13",
    updated_at: "2021-02-02 09:48:17",
    location_id: 1,
    facility_id: null,
    password_changed: true,
    deleted_at: null,
    check_number: 12042317,
    created_by: null,
    updated_by: null,
    deleted_by: null,
    phone_number: "0735124211",
    active: true,
    level_id: 1,
    roles: [
      {
        id: 22,
        name: "STATISTICIANS",
        description: "Council Statisticians",
        deleted_at: null,
        created_at: "2020-08-27 09:56:35",
        updated_at: "2020-08-27 09:57:19",
        display_name: "STATISTICIANS",
        level_id: 4,
        sector_code: "A",
      },
    ],
    location: {
      id: 1,
      name: "Tanzania",
      vote_no: "",
      gn_no: "",
      reg_no: null,
      population: null,
      centroid: null,
      coverage_area: null,
      description: null,
      deleted_at: null,
      level_id: 1,
      admin_area_category_id: null,
      created_at: "2017-08-07 18:35:57",
      updated_at: "2017-08-07 18:35:57",
      active: true,
      council_code: null,
      serial: null,
      village_ward_code: null,
    },
    facility: null,
  },
  {
    id: 47054,
    name: "Abdulhaman Khatibu",
    email: "abdulrahman.hatibu@tamisemi.go.tz",
    created_at: "2019-04-17 12:13:41",
    updated_at: "2021-07-16 23:40:53",
    location_id: 1,
    facility_id: null,
    password_changed: true,
    deleted_at: null,
    check_number: 11411237,
    created_by: null,
    updated_by: null,
    deleted_by: null,
    phone_number: "0688794977",
    active: true,
    level_id: 1,
    roles: [
      {
        id: 6,
        name: "PORALG_APPLICATION_SUPPORT",
        description: "PORALG Application Support",
        deleted_at: null,
        created_at: "2018-03-11 17:16:37",
        updated_at: "2020-08-05 14:46:24",
        display_name: "PORALG APPLICATION SUPPORT",
        level_id: 1,
        sector_code: null,
      },
    ],
    location: {
      id: 1,
      name: "Tanzania",
      vote_no: "",
      gn_no: "",
      reg_no: null,
      population: null,
      centroid: null,
      coverage_area: null,
      description: null,
      deleted_at: null,
      level_id: 1,
      admin_area_category_id: null,
      created_at: "2017-08-07 18:35:57",
      updated_at: "2017-08-07 18:35:57",
      active: true,
      council_code: null,
      serial: null,
      village_ward_code: null,
    },
    facility: null,
  },
  {
    id: 50977,
    name: "Alice Gungi Mwallo",
    email: "alicemwallo124@gmail.com",
    created_at: "2020-03-24 17:08:41",
    updated_at: "2020-03-24 17:36:14",
    location_id: 1,
    facility_id: null,
    password_changed: true,
    deleted_at: null,
    check_number: 8776394,
    created_by: null,
    updated_by: null,
    deleted_by: null,
    phone_number: "0757905154",
    active: true,
    level_id: 1,
    roles: [
      {
        id: 6,
        name: "PORALG_APPLICATION_SUPPORT",
        description: "PORALG Application Support",
        deleted_at: null,
        created_at: "2018-03-11 17:16:37",
        updated_at: "2020-08-05 14:46:24",
        display_name: "PORALG APPLICATION SUPPORT",
        level_id: 1,
        sector_code: null,
      },
    ],
    location: {
      id: 1,
      name: "Tanzania",
      vote_no: "",
      gn_no: "",
      reg_no: null,
      population: null,
      centroid: null,
      coverage_area: null,
      description: null,
      deleted_at: null,
      level_id: 1,
      admin_area_category_id: null,
      created_at: "2017-08-07 18:35:57",
      updated_at: "2017-08-07 18:35:57",
      active: true,
      council_code: null,
      serial: null,
      village_ward_code: null,
    },
    facility: null,
  },
  {
    id: 44488,
    name: "Alliy Khamisy Alliy",
    email: "alliykhamisy@yahoo.com",
    created_at: "2018-09-13 11:26:29",
    updated_at: "2019-06-25 14:25:31",
    location_id: 1,
    facility_id: null,
    password_changed: true,
    deleted_at: null,
    check_number: 8226257,
    created_by: null,
    updated_by: null,
    deleted_by: null,
    phone_number: "0755858889",
    active: true,
    level_id: null,
    roles: [
      {
        id: 6,
        name: "PORALG_APPLICATION_SUPPORT",
        description: "PORALG Application Support",
        deleted_at: null,
        created_at: "2018-03-11 17:16:37",
        updated_at: "2020-08-05 14:46:24",
        display_name: "PORALG APPLICATION SUPPORT",
        level_id: 1,
        sector_code: null,
      },
    ],
    location: {
      id: 1,
      name: "Tanzania",
      vote_no: "",
      gn_no: "",
      reg_no: null,
      population: null,
      centroid: null,
      coverage_area: null,
      description: null,
      deleted_at: null,
      level_id: 1,
      admin_area_category_id: null,
      created_at: "2017-08-07 18:35:57",
      updated_at: "2017-08-07 18:35:57",
      active: true,
      council_code: null,
      serial: null,
      village_ward_code: null,
    },
    facility: null,
  },
  {
    id: 39796,
    name: "ALLY KISUDA",
    email: "ally.ramadhan@tamisemi.go.tz",
    created_at: "2018-04-10 12:37:08",
    updated_at: "2020-10-16 09:26:56",
    location_id: 1,
    facility_id: null,
    password_changed: true,
    deleted_at: null,
    check_number: 9694514,
    created_by: null,
    updated_by: null,
    deleted_by: null,
    phone_number: "0787488328",
    active: true,
    level_id: 1,
    roles: [
      {
        id: 7,
        name: "PORALG_STATISTICS",
        description: "PORALG STATISTICS",
        deleted_at: null,
        created_at: "2018-03-27 08:47:09",
        updated_at: "2018-04-25 10:57:24",
        display_name: "PORALG STATISTICS",
        level_id: 1,
        sector_code: "A",
      },
      {
        id: 18,
        name: "PO-RALG_TECHNICAL",
        description: "PO-RALG Technical",
        deleted_at: null,
        created_at: "2018-07-06 19:23:29",
        updated_at: "2018-07-06 19:23:29",
        display_name: "PO-RALG TECHNICAL",
        level_id: 1,
        sector_code: "A",
      },
      {
        id: 6,
        name: "PORALG_APPLICATION_SUPPORT",
        description: "PORALG Application Support",
        deleted_at: null,
        created_at: "2018-03-11 17:16:37",
        updated_at: "2020-08-05 14:46:24",
        display_name: "PORALG APPLICATION SUPPORT",
        level_id: 1,
        sector_code: null,
      },
      {
        id: 22,
        name: "STATISTICIANS",
        description: "Council Statisticians",
        deleted_at: null,
        created_at: "2020-08-27 09:56:35",
        updated_at: "2020-08-27 09:57:19",
        display_name: "STATISTICIANS",
        level_id: 4,
        sector_code: "A",
      },
    ],
    location: {
      id: 1,
      name: "Tanzania",
      vote_no: "",
      gn_no: "",
      reg_no: null,
      population: null,
      centroid: null,
      coverage_area: null,
      description: null,
      deleted_at: null,
      level_id: 1,
      admin_area_category_id: null,
      created_at: "2017-08-07 18:35:57",
      updated_at: "2017-08-07 18:35:57",
      active: true,
      council_code: null,
      serial: null,
      village_ward_code: null,
    },
    facility: null,
  },
  {
    id: 50259,
    name: "Ally Nkullo",
    email: "ahnkullo@gmail.com",
    created_at: "2020-01-24 11:07:53",
    updated_at: "2020-02-27 13:38:22",
    location_id: 1,
    facility_id: null,
    password_changed: true,
    deleted_at: null,
    check_number: 112233667,
    created_by: null,
    updated_by: null,
    deleted_by: null,
    phone_number: "0755858634",
    active: true,
    level_id: 1,
    roles: [
      {
        id: 18,
        name: "PO-RALG_TECHNICAL",
        description: "PO-RALG Technical",
        deleted_at: null,
        created_at: "2018-07-06 19:23:29",
        updated_at: "2018-07-06 19:23:29",
        display_name: "PO-RALG TECHNICAL",
        level_id: 1,
        sector_code: "A",
      },
    ],
    location: {
      id: 1,
      name: "Tanzania",
      vote_no: "",
      gn_no: "",
      reg_no: null,
      population: null,
      centroid: null,
      coverage_area: null,
      description: null,
      deleted_at: null,
      level_id: 1,
      admin_area_category_id: null,
      created_at: "2017-08-07 18:35:57",
      updated_at: "2017-08-07 18:35:57",
      active: true,
      council_code: null,
      serial: null,
      village_ward_code: null,
    },
    facility: null,
  },
  {
    id: 45210,
    name: "Ally Rashid Ally",
    email: "ally.rashid@tamisemi.go.tz",
    created_at: "2018-10-26 10:43:01",
    updated_at: "2020-03-06 17:50:08",
    location_id: 1,
    facility_id: null,
    password_changed: true,
    deleted_at: null,
    check_number: 9744648,
    created_by: null,
    updated_by: null,
    deleted_by: null,
    phone_number: "0754634190",
    active: true,
    level_id: null,
    roles: [
      {
        id: 6,
        name: "PORALG_APPLICATION_SUPPORT",
        description: "PORALG Application Support",
        deleted_at: null,
        created_at: "2018-03-11 17:16:37",
        updated_at: "2020-08-05 14:46:24",
        display_name: "PORALG APPLICATION SUPPORT",
        level_id: 1,
        sector_code: null,
      },
    ],
    location: {
      id: 1,
      name: "Tanzania",
      vote_no: "",
      gn_no: "",
      reg_no: null,
      population: null,
      centroid: null,
      coverage_area: null,
      description: null,
      deleted_at: null,
      level_id: 1,
      admin_area_category_id: null,
      created_at: "2017-08-07 18:35:57",
      updated_at: "2017-08-07 18:35:57",
      active: true,
      council_code: null,
      serial: null,
      village_ward_code: null,
    },
    facility: null,
  },
  {
    id: 49816,
    name: "Ally Yohana Kananika",
    email: "allykananika@yahoo.com",
    created_at: "2019-11-18 13:21:49",
    updated_at: "2019-11-18 13:26:00",
    location_id: 1,
    facility_id: null,
    password_changed: true,
    deleted_at: null,
    check_number: 12234476,
    created_by: null,
    updated_by: null,
    deleted_by: null,
    phone_number: "0687871275",
    active: true,
    level_id: null,
    roles: [
      {
        id: 6,
        name: "PORALG_APPLICATION_SUPPORT",
        description: "PORALG Application Support",
        deleted_at: null,
        created_at: "2018-03-11 17:16:37",
        updated_at: "2020-08-05 14:46:24",
        display_name: "PORALG APPLICATION SUPPORT",
        level_id: 1,
        sector_code: null,
      },
    ],
    location: {
      id: 1,
      name: "Tanzania",
      vote_no: "",
      gn_no: "",
      reg_no: null,
      population: null,
      centroid: null,
      coverage_area: null,
      description: null,
      deleted_at: null,
      level_id: 1,
      admin_area_category_id: null,
      created_at: "2017-08-07 18:35:57",
      updated_at: "2017-08-07 18:35:57",
      active: true,
      council_code: null,
      serial: null,
      village_ward_code: null,
    },
    facility: null,
  },
  {
    id: 48266,
    name: "Aloyce Maziku",
    email: "amaziku2@yahoo.com",
    created_at: "2019-07-30 12:32:24",
    updated_at: "2019-07-30 12:34:40",
    location_id: 1,
    facility_id: null,
    password_changed: true,
    deleted_at: null,
    check_number: 784642999,
    created_by: null,
    updated_by: null,
    deleted_by: null,
    phone_number: "0784642999",
    active: true,
    level_id: null,
    roles: [
      {
        id: 6,
        name: "PORALG_APPLICATION_SUPPORT",
        description: "PORALG Application Support",
        deleted_at: null,
        created_at: "2018-03-11 17:16:37",
        updated_at: "2020-08-05 14:46:24",
        display_name: "PORALG APPLICATION SUPPORT",
        level_id: 1,
        sector_code: null,
      },
    ],
    location: {
      id: 1,
      name: "Tanzania",
      vote_no: "",
      gn_no: "",
      reg_no: null,
      population: null,
      centroid: null,
      coverage_area: null,
      description: null,
      deleted_at: null,
      level_id: 1,
      admin_area_category_id: null,
      created_at: "2017-08-07 18:35:57",
      updated_at: "2017-08-07 18:35:57",
      active: true,
      council_code: null,
      serial: null,
      village_ward_code: null,
    },
    facility: null,
  },
  {
    id: 44491,
    name: "Amina Chinja",
    email: "aminachinja@gmail.com",
    created_at: "2018-09-13 11:39:31",
    updated_at: "2018-12-14 13:02:02",
    location_id: 1,
    facility_id: null,
    password_changed: false,
    deleted_at: null,
    check_number: 5602513,
    created_by: null,
    updated_by: null,
    deleted_by: null,
    phone_number: "0755661200",
    active: true,
    level_id: null,
    roles: [
      {
        id: 12,
        name: "DT",
        description: "District Tresurer",
        deleted_at: null,
        created_at: "2018-03-29 09:57:49",
        updated_at: "2018-03-29 09:57:49",
        display_name: "DT",
        level_id: 4,
        sector_code: "A",
      },
    ],
    location: {
      id: 1,
      name: "Tanzania",
      vote_no: "",
      gn_no: "",
      reg_no: null,
      population: null,
      centroid: null,
      coverage_area: null,
      description: null,
      deleted_at: null,
      level_id: 1,
      admin_area_category_id: null,
      created_at: "2017-08-07 18:35:57",
      updated_at: "2017-08-07 18:35:57",
      active: true,
      council_code: null,
      serial: null,
      village_ward_code: null,
    },
    facility: null,
  },
];
