# config valid for current version and patch releases of Capistrano
# lock "~> 3.17.0"

set :application, 'ui'
set :repo_url, 'git@github.com:PO-RALG/ffars-client.git'

# Display colorful log messages when capistrano is working
set :format, :pretty
set :log_level, :debug
set :pty, true
set :tmp_dir, '/home/deploy/tmp'

# set :copy_files, ['public/src', 'node_modules']
set :deploy_via, :remote_cache
# shared between all releases. for instance, files that are generated by the users
set :linked_files, %w[.env .env.production]
# set :linked_dirs, fetch(:linked_dirs, []) + %w[node_modules]

set :ssh_options, {
  verify_host_key: :secure,
  forward_agent: true
}

set :nvm_type, :user
set :nvm_node, 'v16.15.1'

namespace :deploy do
  set :yarn_target_path, nil
  set :yarn_flags, '--production'
  set :yarn_roles, :all
  set :yarn_env_variables, {}
  set :yarn_bin, :yarn
  desc 'Restart'
  task :restart do
    on roles(:app) do
      within current_path  do
        execute :yarn, 'install -s' # install dependencies silently
        # execute :yarn, 'build -s' # build the app silently
        execute fetch(:yarn_bin), 'build', fetch(:yarn_flags)
      end
    end
  end

  after 'deploy:publishing', 'restart'
  after 'deploy:publishing', 'nginx:restart' # restart nginx
end

# Default value for keep_releases is 5
set :keep_releases, 5
