name: Deploy Kofference.js App

on:
  push:
    branches:
      - gallery_c

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install -f

      - name: Build Vue.js App
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: 196.192.73.26
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "dist/"
          target: "/var/www/html/dist/"